env:
  es2021: true
  node: true
globals:
  describe: readonly
  it: readonly
  test: readonly
  expect: readonly
  vi: readonly
  beforeEach: readonly
  afterEach: readonly
  beforeAll: readonly
  afterAll: readonly
extends:
  - standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
