name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Flake8
        run: pip install flake8
      - name: Flake8 Check
        run: flake8 python --exit-zero --statistics --max-line-length=120
